<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-6 col-sm-12">
      <div class="card border-0 shadow-lg mt-5">
        <div class="card-body my-auto card-form">
          <div class=" text-center">
            <h1>Cadastre-se</h1>
          </div>
          <form action="/registrar" method="post">
          <div class="form-group">
                <label for="nome">Nome:</label>
                <input type="text" value="<?= $this->view->usuario['nome'] ?>" class="form-control" name="nome" id="nome" aria-describedby="name" placeholder="Ex. Brenda Almeida" required autofocus>
            </div>
            <div class="form-group">
                <label for="email">E-mail:</label>
                <input type="email" value="<?= $this->view->usuario['email'] ?>" class="form-control" name="email" id="email" aria-describedby="emailHelp" placeholder="Ex. brenda@email.com" required>
            </div>
            <div class="form-group">
                <label for="senha">Senha:</label>
                <input type="password" class="form-control" name="senha" id="senha" placeholder="Digite sua Senha" required>
            </div>            
            <button type="submit" class="btn">
                Cadastrar
            </button>
            <?php if($this->view->erroCadastro) { ?>
              <span class="form-text text-danger">*Erro ao tentar realizar o cadastro. Informações inválidas, confira os campos.</span>
            <?php } ?>

            <?php if($this->view->erroCadastroEmail) { ?>
              <span class="form-text text-danger">*Email já cadastrado.</span>
            <?php } ?>

            <div class="cadastro">
              <span>Já possui login?</span>
              <a href="/login">Login</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>