<?php if($this->view->sucessoCadastro) { ?>
  <div class="cadastro-sucesso text-center">
    <p>Cadastrado com sucesso</p>
  </div>     
<?php } ?>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-6 col-sm-12">
      <div class="card border-0 shadow-lg card-form mt-5">
        <div class="card-body my-auto">
          <div class=" text-center">
            <h1>Login</h1>
          </div>
          <form action="/autenticar" method="post">
            <div class="form-group">
                <label for="email">E-mail:</label>
                <input type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp" placeholder="Ex.: brenda@mail.com" required autofocus>
            </div>
            <div class="form-group">
                <label for="senha">Senha:</label>
                <input type="password" class="form-control" name="senha" id="senha" placeholder="Digite sua Senha" required>
            </div>            
            <button type="submit" class="btn">
                Login
            </button>
            
            <?php if($this->view->login == 'erro') { ?>
              <span class="text text-danger">*E-mail e/ou senha inválido(s)</span>
            <?php } ?>

            <div class="cadastro">
              <span>Ainda não é usuário ?</span>
              <a href="/cadastro">Inscreva-se aqui</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>